### ISSUE TITLE
Автоматически добавлять к картинками в новостях responsive-классы

### ISSUE THREAD

**Issue by samdark** [samdark/yiiframework-ru#87]
Должно быть `<img class="img img-responsive"`.

**Comment by alexantr** [comment]
Проще в CSS добавить
```css
.post-item img {
    max-width: 100%;
    height: auto;
}
```
